services:

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_DOCKER_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./auth_service/src:/app/src
    depends_on:
      - postgres
      - kafka

  ch_exporter:
    build:
      context: ./ch_exporter
      dockerfile: Dockerfile
    environment:
      - CLICKHOUSE_URL=${CLICKHOUSE_URL}
      - EXPORTER_TOKEN=${EXPORTER_TOKEN}
    depends_on:
      - clickhouse

  telemetry_service:
    build:
      context: ./telemetry_service
      dockerfile: Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    ports:
      - "8001:8001"
    volumes:
      - ./telemetry_service/src:/app/src
    depends_on:
      - kafka

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_NODE_ID: "1"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      CLUSTER_ID: ${CLUSTER_ID}
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  postgres_data:
  clickhouse_data:
  kafka_data:
